name: Test Agent Compatibility

on:
  # TODO: Remove after finishing the implementation
  # This job should run after the PR is merged
  pull_request:
    branches:
      - main
      - "[0-9]+.[0-9]+"
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - "[0-9]+.[0-9]+"

jobs:
  test-agents:
    name: Agent Compatibility Test
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - agent-version: '8.13.1'
            package-version: '1.8.1'
          - agent-version: '8.12.2'
            package-version: '1.7.4'
          - agent-version: '8.11.4'
            package-version: '1.6.5'
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Hermit Environment
        uses: ./.github/actions/hermit
        with:
          init-tools: 'true'

      - name: Init Integration
        uses: ./.github/actions/init-integration
        with:
          elk-version: ${{ env.ELK_VERSION }} # Initialized in hermit.hcl
          build-cloudbeat: 'false'

      - id: google-auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Run Agent ${{ matrix.agent-version }}
        shell: bash
        env:
          ES_HOST: http://localhost:9200
          ES_USERNAME: elastic
          ES_PASSWORD: changeme
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_TEST_ACC }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_TEST_ACC }}
          AZURE_CLIENT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}
          AZURE_TENANT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}
          AZURE_CLIENT_SECRET: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}
        run: ./.ci/scripts/run-agent.sh ${{ matrix.agent-version }} ${{ matrix.package-version }}

      - name: Wait for cloudbeat to send some events
        shell: bash
        run: sleep 60

      - name: Check for findings
        working-directory: ./tests
        env:
          USE_K8S: "false"
        shell: bash
        run: |
          testmarker="cspm"
          # Azure manual credentials are not supported in 8.11
          if [[ "${{ matrix.agent-version }}" == *"8.11"* ]]; then
            testmarker="cspm and not azure"
          fi
          poetry run pytest -k "$testmarker" --alluredir=./allure/results/ --clean-alluredir --maxfail=2
